name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4

      # Connexion à Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build et push backend
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./back
          file: ./back/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-back:${{ github.sha }}

      # Build et push frontend
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./front
          file: ./front/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/bobapp-front:${{ github.sha }}
