name: SonarQube Front
on:
  push:
    branches:
      - 'feature/**'
      - 'develop'
      - 'release/**'
      - 'hotfix/**'
    paths:
      - 'front/**'
  pull_request:
    paths:
      - 'front/**' 

jobs:
  sonarqube:
    name: SonarQube Front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.15.1'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: front

      - name: Run Angular tests with coverage
        run: npm run test
        working-directory: front

      - name: Build and analyze with Sonar
        uses: SonarSource/sonarcloud-github-action@v3
        with: 
          projectBaseDir: ./front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          
