name: SonarQube Front
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarqube:
    name: SonarQube Front
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Angular tests with coverage
        run: npm run test
        working-directory: front

      - name: Build and analyze with Sonar
        uses: SonarSource/sonarcloud-github-action@v3
        with: 
          projectBaseDir: ./front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_FRONT }}
          
